#ifndef WIDGETENUM_H
#define WIDGETENUM_H

enum RuntimeScreenType { RUNTIME_A, RUNTIME_B, RUNTIME_C, RUNTIME_D, RUNTIME_E, RUNTIME_DL1 , RUNTIME_ES, RUNTIME_MULTI, RUNTIME_DL1_B, RUNTIME_ES_B};
enum SetupMenuType { SETUP_MENU, BOAT_MENU };

enum class InformationSource { W_TEMP, SOG_LONG, SOG_TRA, SOG, STW_LONG, STW_TRA, STW, STW_DL1, ALARM_HIGH, ALARM_LOW, DEPTH, TRIP, TOTAL, DRAFT, GPS_SOG, GAIN, SHALLOW_ALARM, DEEP_ALARM };
enum class SystemEnum { DL1_SYSTEM, DL2_SYSTEM_1, DL2_SYSTEM_2, ES_SYSTEM };

#endif // WIDGETENUM_H
