include(keyboard/keyboard.pri)

SOURCES += $$PWD/screen/base_runtime_setup_screen.cpp \
    $$PWD/screen/base_screen.cpp \
    $$PWD/screen/boat_menu_screen.cpp \
    $$PWD/screen/cu_setup_screen.cpp \
    $$PWD/screen/dl1_alert_setup_screen.cpp \
    $$PWD/screen/dl1_aux_setup_screen.cpp \
    $$PWD/screen/dl1_calibration_setup_screen.cpp \
    $$PWD/screen/dl1_communication_setup_screen.cpp \
    $$PWD/screen/dl1_diagnostic_setup_screen.cpp \
    $$PWD/screen/dl1_runtime_a_setup_screen.cpp \
    $$PWD/screen/dl1_runtime_b_setup_screen.cpp \
    $$PWD/screen/dl1_runtime_setup_screen.cpp \
    $$PWD/screen/dl1_setup_screen.cpp \
    $$PWD/screen/dl2_alert_setup_screen.cpp \
    $$PWD/screen/dl2_aux_setup_screen.cpp \
    $$PWD/screen/dl2_calibration_inst_angle_setup_screen.cpp \
    $$PWD/screen/dl2_calibration_setup_screen.cpp \
    $$PWD/screen/dl2_calibration_speed_auto_setup_screen.cpp \
    $$PWD/screen/dl2_calibration_speed_manual_gps_setup_screen.cpp \
    $$PWD/screen/dl2_calibration_speed_manual_setup_screen.cpp \
    $$PWD/screen/dl2_calibration_speed_sea_setup_screen.cpp \
    $$PWD/screen/dl2_calibration_speed_setup_screen.cpp \
    $$PWD/screen/dl2_calibration_status_setup_screen.cpp \
    $$PWD/screen/dl2_calibration_temp_setup_screen.cpp \
    $$PWD/screen/dl2_calibration_tilt_setup_screen.cpp \
    $$PWD/screen/dl2_communication_setup_screen.cpp \
    $$PWD/screen/dl2_diagnostic_setup_screen.cpp \
    $$PWD/screen/dl2_jb70_setup_screen.cpp \
    $$PWD/screen/dl2_runtime_a_setup_screen.cpp \
    $$PWD/screen/dl2_runtime_b_setup_screen.cpp \
    $$PWD/screen/dl2_runtime_c_setup_screen.cpp \
    $$PWD/screen/dl2_runtime_d_setup_screen.cpp \
    $$PWD/screen/dl2_runtime_e_setup_screen.cpp \
    $$PWD/screen/dl2_runtime_setup_screen.cpp \
    $$PWD/screen/dl2_setup_options_screen.cpp \
    $$PWD/screen/dl2_setup_screen.cpp \
    $$PWD/screen/dl2_setup_setup_screen.cpp \
    $$PWD/screen/es_alert_setup_screen.cpp \
    $$PWD/screen/es_aux_setup_screen.cpp \
    $$PWD/screen/es_communication_setup_screen.cpp \
    $$PWD/screen/es_diagnostic_setup_screen.cpp \
    $$PWD/screen/es_history_setup_screen.cpp \
    $$PWD/screen/es_jb70_setup_screen.cpp \
    $$PWD/screen/es_runtime_a_setup_screen.cpp \
    $$PWD/screen/es_runtime_b_setup_screen.cpp \
    $$PWD/screen/es_runtime_screen.cpp \
    $$PWD/screen/es_runtime_setup_screen.cpp \
    $$PWD/screen/es_setup_screen.cpp \
    $$PWD/screen/multi_setup_screen.cpp \
    $$PWD/screen/runtime_screen.cpp \
    $$PWD/screen/setup_menu_screen.cpp \
    $$PWD/screen/setup_screen.cpp \
    $$PWD/screen/system_setup_screen.cpp \
    $$PWD/widget/arrow_widget.cpp \
    $$PWD/widget/background_widget.cpp \
    $$PWD/widget/boat_button.cpp \
    $$PWD/widget/brightness_widget.cpp \
    $$PWD/widget/button.cpp \
    $$PWD/widget/calibration_graph_widget.cpp \
    $$PWD/widget/display_alive_widget.cpp \
    $$PWD/widget/dl1_runtime_widget_b.cpp \
    $$PWD/widget/es_runtime_widget_b.cpp \
    $$PWD/widget/horizontal_item_widget.cpp \
    $$PWD/widget/horizontal_item_widget_container.cpp \
    $$PWD/widget/information_widget.cpp \
    $$PWD/widget/item_widget.cpp \
    $$PWD/widget/item_widget_container.cpp \
    $$PWD/widget/leg_button.cpp \
    $$PWD/widget/navigation_widget.cpp \
    $$PWD/widget/runtime_widget.cpp \
    $$PWD/widget/runtime_widget_a.cpp \
    $$PWD/widget/runtime_widget_b.cpp \
    $$PWD/widget/runtime_widget_c.cpp \
    $$PWD/widget/runtime_widget_d.cpp \
    $$PWD/widget/runtime_widget_dl1.cpp \
    $$PWD/widget/runtime_widget_e.cpp \
    $$PWD/widget/runtime_widget_es.cpp \
    $$PWD/widget/scalable_widget.cpp \
    $$PWD/widget/selectable_bool_item_widget.cpp \
    $$PWD/widget/selectable_enum_item_widget.cpp \
    $$PWD/widget/selectable_float_item_widget.cpp \
    $$PWD/widget/selectable_int_item_widget.cpp \
    $$PWD/widget/selectable_ip_item_widget.cpp \
    $$PWD/widget/selectable_item_widget.cpp \
    $$PWD/widget/selectable_item_widget_container.cpp \
    $$PWD/widget/selectable_string_item_widget.cpp \
    $$PWD/widget/system_widget.cpp \
    $$PWD/widget/system_widget_container.cpp \
    $$PWD/widget/title_widget.cpp \
    $$PWD/widget/transparent_info_button.cpp \
    $$PWD/widget/up_down_widget.cpp \
    $$PWD/widget/validator.cpp \
    $$PWD/widget/password_widget.cpp \
    $$PWD/navigation_controller.cpp \
    $$PWD/screen/es_setup_setup_screen.cpp \
    $$PWD/screen/es_setup_transducer_select_screen.cpp \
    $$PWD/widget/display_button.cpp \
    $$PWD/widget/split_es_runtime_widget.cpp \
    $$PWD/widget/system_menu_widget_container.cpp \
    $$PWD/widget/system_setup_widget.cpp \
    $$PWD/widget/system_setup_widget_container.cpp



HEADERS  += $$PWD/screen/base_runtime_setup_screen.h \
    $$PWD/screen/base_screen.h \
    $$PWD/screen/boat_menu_screen.h \
    $$PWD/screen/cu_setup_screen.h \
    $$PWD/screen/dl1_alert_setup_screen.h \
    $$PWD/screen/dl1_aux_setup_screen.h \
    $$PWD/screen/dl1_calibration_setup_screen.h \
    $$PWD/screen/dl1_communication_setup_screen.h \
    $$PWD/screen/dl1_diagnostic_setup_screen.h \
    $$PWD/screen/dl1_runtime_a_setup_screen.h \
    $$PWD/screen/dl1_runtime_b_setup_screen.h \
    $$PWD/screen/dl1_runtime_setup_screen.h \
    $$PWD/screen/dl1_setup_screen.h \
    $$PWD/screen/dl2_alert_setup_screen.h \
    $$PWD/screen/dl2_aux_setup_screen.h \
    $$PWD/screen/dl2_calibration_inst_angle_setup_screen.h \
    $$PWD/screen/dl2_calibration_setup_screen.h \
    $$PWD/screen/dl2_calibration_speed_auto_setup_screen.h \
    $$PWD/screen/dl2_calibration_speed_manual_gps_setup_screen.h \
    $$PWD/screen/dl2_calibration_speed_manual_setup_screen.h \
    $$PWD/screen/dl2_calibration_speed_sea_setup_screen.h \
    $$PWD/screen/dl2_calibration_speed_setup_screen.h \
    $$PWD/screen/dl2_calibration_status_setup_screen.h \
    $$PWD/screen/dl2_calibration_temp_setup_screen.h \
    $$PWD/screen/dl2_calibration_tilt_setup_screen.h \
    $$PWD/screen/dl2_communication_setup_screen.h \
    $$PWD/screen/dl2_diagnostic_setup_screen.h \
    $$PWD/screen/dl2_jb70_setup_screen.h \
    $$PWD/screen/dl2_runtime_a_setup_screen.h \
    $$PWD/screen/dl2_runtime_b_setup_screen.h \
    $$PWD/screen/dl2_runtime_c_setup_screen.h \
    $$PWD/screen/dl2_runtime_d_setup_screen.h \
    $$PWD/screen/dl2_runtime_e_setup_screen.h \
    $$PWD/screen/dl2_runtime_setup_screen.h \
    $$PWD/screen/dl2_setup_options_screen.h \
    $$PWD/screen/dl2_setup_screen.h \
    $$PWD/screen/dl2_setup_setup_screen.h \
    $$PWD/screen/es_alert_setup_screen.h \
    $$PWD/screen/es_aux_setup_screen.h \
    $$PWD/screen/es_communication_setup_screen.h \
    $$PWD/screen/es_diagnostic_setup_screen.h \
    $$PWD/screen/es_history_setup_screen.h \
    $$PWD/screen/es_jb70_setup_screen.h \
    $$PWD/screen/es_runtime_a_setup_screen.h \
    $$PWD/screen/es_runtime_b_setup_screen.h \
    $$PWD/screen/es_runtime_screen.h \
    $$PWD/screen/es_runtime_setup_screen.h \
    $$PWD/screen/es_setup_screen.h \
    $$PWD/screen/multi_setup_screen.h \
    $$PWD/screen/runtime_screen.h \
    $$PWD/screen/setup_menu_screen.h \
    $$PWD/screen/setup_screen.h \
    $$PWD/screen/system_setup_screen.h \
    $$PWD/widget/arrow_widget.h \
    $$PWD/widget/background_widget.h \
    $$PWD/widget/boat_button.h \
    $$PWD/widget/brightness_widget.h \
    $$PWD/widget/button.h \
    $$PWD/widget/calibration_graph_widget.h \
    $$PWD/widget/display_alive_widget.h \
    $$PWD/widget/dl1_runtime_widget_b.h \
    $$PWD/widget/es_runtime_widget_b.h \
    $$PWD/widget/horizontal_item_widget.h \
    $$PWD/widget/horizontal_item_widget_container.h \
    $$PWD/widget/information_widget.h \
    $$PWD/widget/item_widget.h \
    $$PWD/widget/item_widget_container.h \
    $$PWD/widget/leg_button.h \
    $$PWD/widget/navigation_widget.h \
    $$PWD/widget/runtime_widget.h \
    $$PWD/widget/runtime_widget_a.h \
    $$PWD/widget/runtime_widget_b.h \
    $$PWD/widget/runtime_widget_c.h \
    $$PWD/widget/runtime_widget_d.h \
    $$PWD/widget/runtime_widget_dl1.h \
    $$PWD/widget/runtime_widget_e.h \
    $$PWD/widget/runtime_widget_es.h \
    $$PWD/widget/scalable_widget.h \
    $$PWD/widget/selectable_bool_item_widget.h \
    $$PWD/widget/selectable_enum_item_widget.h \
    $$PWD/widget/selectable_float_item_widget.h \
    $$PWD/widget/selectable_int_item_widget.h \
    $$PWD/widget/selectable_ip_item_widget.h \
    $$PWD/widget/selectable_item_widget.h \
    $$PWD/widget/selectable_item_widget_container.h \
    $$PWD/widget/selectable_string_item_widget.h \
    $$PWD/widget/system_widget.h \
    $$PWD/widget/system_widget_container.h \
    $$PWD/widget/title_widget.h \
    $$PWD/widget/transparent_info_button.h \
    $$PWD/widget/up_down_widget.h \
    $$PWD/widget/validator.h \
    $$PWD/widget/password_widget.h \
    $$PWD/navigation_controller.h \
    $$PWD/widget_enum.h \
    $$PWD/screen/es_setup_setup_screen.h \
    $$PWD/screen/es_setup_transducer_select_screen.h \
    $$PWD/widget/display_button.h \
    $$PWD/widget/split_es_runtime_widget.h \
    $$PWD/widget/system_menu_widget_container.h \
    $$PWD/widget/system_setup_widget.h \
    $$PWD/widget/system_setup_widget_container.h
