#ifndef WIDGET_ENUM_H
#define WIDGET_ENUM_H

enum RuntimeScreenType { RUNTIME_A, RUNTIME_B, RUNTIME_C, RUNTIME_D, RUNTIME_E, RUNTIME_DL1 , RUNTIME_ES, RUNTIME_DL1_B, RUNTIME_ES_B};
enum SetupMenuType { SETUP_MENU, BOAT_MENU };
enum SetupScreenType { DL1_ALERT_SETUP, DL1_AUX_SETUP, DL1_COMMUNICATION_SETUP, DL1_CALIBRATION_SETUP, DL1_DIAGNOSTIC_SETUP, DL1_RUNTIME_SETUP, DL1_SETUP, DL2_ALERT_SETUP, DL2_AUX_SETUP, DL2_CALIBRATION_SETUP, DL2_COMMUNICATION_SETUP, DL2_DIAGNOSTIC_SETUP, DL2_JB70_SETUP, DL2_RUNTIME_SETUP, DL2_SETUP, ES_ALERT_SETUP, ES_AUX_SETUP, ES_COMMUNICATION_SETUP, ES_DIAGNOSTIC_SETUP, ES_JB70_SETUP, ES_HISTORY_SETUP, ES_RUNTIME_SETUP, ES_SETUP};

enum class InformationSource { W_TEMP, SOG_LONG, SOG_TRA, SOG, STW_LONG, STW_TRA, STW, STW_DL1, ALARM_HIGH, ALARM_LOW, DEPTH, TRIP, TOTAL, DRAFT, GPS_SOG, GAIN, SHALLOW_ALARM, DEEP_ALARM };
enum class SystemEnum { DL1_SYSTEM, DL2_SYSTEM, ES_SYSTEM };

enum RowIndexParity { ODD, EVEN };
enum VerticalOrientation { FORWARD, BACKWARD };

#endif
