#ifndef NMEA_INCLUDE_H
#define NMEA_INCLUDE_H

#include "nmea_message.h"
#include "msg_commands.h"
#include "msg/msg_alma_speed.h"
#include "msg/msg_alma_temp.h"
#include "msg/msg_alr.h"
#include "msg/msg_blnk.h"
#include "msg/msg_cfg.h"
#include "msg/msg_dat.h"
#include "msg/msg_gga.h"
#include "msg/msg_hdt.h"
#include "msg/msg_mtw.h"
#include "msg/msg_mtwf.h"
#include "msg/msg_png.h"
#include "msg/msg_rot.h"
#include "msg/msg_snf.h"
#include "msg/msg_tst.h"
#include "msg/msg_vbw.h"
#include "msg/msg_vbwf.h"
#include "msg/msg_vhw.h"
#include "msg/msg_vlw.h"
#include "msg/msg_vtg.h"
#include "msg/msg_dpt.h"
#include "msg/msg_acm.h"
#include "msg/msg_ack.h"
#include "msg/msg_alc.h"
#include "msg/msg_alf.h"
#include "msg/msg_arc.h"
#include "msg/msg_dlr.h"
#include "msg/msg_dli.h"
#include "msg/msg_hbt.h"
#include "msg/msg_rmc.h"
#include "msg/msg_zda.h"
#include "msg/msg_ztg.h"
#include "msg/msg_sfs.h"
#include "msg/msg_alrs.h"
#include "msg/msg_error_table.h"
#include "msg/msg_error_code.h"
#include "msg/msg_vmpcgter.h"
#include "msg/msg_cppc.h"
#include "msg/msg_rstt.h"
#include "msg/msg_rcf.h"
#include "msg/msg_gcf.h"
#include "msg/msg_scf.h"
#include "msg/msg_ddc.h"
#include "msg/msg_ths.h"
#include "msg/msg_gll.h"
#include "msg/msg_err.h"
#include "msg/msg_rsto.h"
#include "msg/msg_datr.h"
#include "msg/msg_stl.h"
#include "msg/msg_cur.h"
#include "msg/msg_ver.h"

#include "msg/msg_dlm.h"

#include "msg/msg_icm.h"
#include "msg/msg_idm.h"

#include "msg/msg_dtl.h"
#include "msg/msg_saf.h"

#include "msg/msg_unknown.h" // used if received message is not implemented

#include "msg/msg_secu.h"

// TESTING!!!
#include "msg/msg_info.h"

#endif
